/* ============================================================
   Bunny Stream -> js/videos.generated.js sync

   Usage:
     1. Copy bunny.config.example.json to bunny.config.local.json
        and fill in your real libraryId, apiKey, and cdnHostname.
        (bunny.config.local.json holds a secret — don't share it.)
     2. node scripts/sync-bunny.js
     3. Reload index.html. Every finished video in your Bunny library
        now has a card. New ones default to category "uncategorized" —
        tag them by editing js/overrides.json (keyed by video GUID,
        see the _comment key in that file for the shape) and re-run.

   This script only reads from Bunny and writes js/videos.generated.js
   plus the two CONFIG lines in js/data.js. It never touches your
   overrides file.
   ============================================================ */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const CONFIG_PATH = path.join(ROOT, "bunny.config.local.json");
const OVERRIDES_PATH = path.join(ROOT, "js", "overrides.json");
const DATA_JS_PATH = path.join(ROOT, "js", "data.js");
const OUTPUT_PATH = path.join(ROOT, "js", "videos.generated.js");

const STATUS_FINISHED = 4;

function loadConfig() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.error(
      `Missing ${path.relative(ROOT, CONFIG_PATH)}.\n` +
        `Copy bunny.config.example.json to bunny.config.local.json and fill in your real values first.`
    );
    process.exit(1);
  }
  const cfg = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
  for (const key of ["libraryId", "apiKey", "cdnHostname"]) {
    if (!cfg[key] || String(cfg[key]).startsWith("your ")) {
      console.error(`bunny.config.local.json is missing a real value for "${key}".`);
      process.exit(1);
    }
  }
  return cfg;
}

function loadOverrides() {
  if (!fs.existsSync(OVERRIDES_PATH)) return {};
  const raw = JSON.parse(fs.readFileSync(OVERRIDES_PATH, "utf8"));
  delete raw._comment;
  return raw;
}

function formatDuration(totalSeconds) {
  const sec = Math.max(0, Math.round(totalSeconds || 0));
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = sec % 60;
  const ss = String(s).padStart(2, "0");
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${ss}`;
  return `${m}:${ss}`;
}

async function fetchAllVideos(cfg) {
  const items = [];
  let page = 1;
  const itemsPerPage = 100;

  while (true) {
    const url = `https://video.bunnycdn.com/library/${cfg.libraryId}/videos?page=${page}&itemsPerPage=${itemsPerPage}&orderBy=date`;
    const res = await fetch(url, {
      headers: { AccessKey: cfg.apiKey, accept: "application/json" },
    });
    if (!res.ok) {
      const body = await res.text().catch(() => "");
      throw new Error(`Bunny API request failed (${res.status} ${res.statusText}): ${body}`);
    }
    const data = await res.json();
    if (!Array.isArray(data.items)) {
      throw new Error(`Unexpected response shape from Bunny API: ${JSON.stringify(data).slice(0, 300)}`);
    }
    items.push(...data.items);
    const totalItems = data.totalItems ?? items.length;
    if (items.length >= totalItems || data.items.length === 0) break;
    page += 1;
  }

  return items;
}

function buildVideoObject(raw, overrides) {
  const guid = raw.guid;
  const ov = overrides[guid] || {};

  return {
    id: guid,
    title: ov.title || raw.title || "Untitled video",
    category: ov.category || "uncategorized",
    platform: "bunny",
    bunnyVideoId: guid,
    level: ov.level || "Uncategorized",
    duration: formatDuration(raw.length),
    tags: Array.isArray(ov.tags) ? ov.tags : [],
    description: ov.description || "",
    featured: Boolean(ov.featured),
  };
}

function serializeVideos(videos) {
  const lines = videos.map((v) => {
    const fields = [
      `    id: ${JSON.stringify(v.id)},`,
      `    title: ${JSON.stringify(v.title)},`,
      `    category: ${JSON.stringify(v.category)},`,
      `    platform: ${JSON.stringify(v.platform)},`,
      `    bunnyVideoId: ${JSON.stringify(v.bunnyVideoId)},`,
      `    level: ${JSON.stringify(v.level)},`,
      `    duration: ${JSON.stringify(v.duration)},`,
      `    tags: ${JSON.stringify(v.tags)},`,
      `    description: ${JSON.stringify(v.description)},`,
    ];
    if (v.featured) fields.push(`    featured: true,`);
    return `  {\n${fields.join("\n")}\n  },`;
  });

  return (
    `/* ============================================================\n` +
    `   AUTO-GENERATED by scripts/sync-bunny.js — do not hand-edit.\n` +
    `   Generated ${new Date().toISOString()} from your Bunny Stream library.\n` +
    `   Tag videos by editing js/overrides.json, then re-run the sync.\n` +
    `   ============================================================ */\n` +
    `const VIDEOS = [\n${lines.join("\n")}\n];\n`
  );
}

function updateDataJsConfig(cfg) {
  let text = fs.readFileSync(DATA_JS_PATH, "utf8");
  text = text.replace(/bunnyLibraryId:\s*"[^"]*"/, `bunnyLibraryId: ${JSON.stringify(String(cfg.libraryId))}`);
  text = text.replace(/bunnyCdnHostname:\s*"[^"]*"/, `bunnyCdnHostname: ${JSON.stringify(cfg.cdnHostname)}`);
  fs.writeFileSync(DATA_JS_PATH, text);
}

async function main() {
  const cfg = loadConfig();
  const overrides = loadOverrides();

  console.log(`Fetching videos from Bunny library ${cfg.libraryId}...`);
  const raw = await fetchAllVideos(cfg);

  const finished = raw.filter((v) => v.status === STATUS_FINISHED);
  const stillProcessing = raw.length - finished.length;

  const videos = finished
    .map((v) => buildVideoObject(v, overrides))
    .sort((a, b) => a.title.localeCompare(b.title));

  fs.writeFileSync(OUTPUT_PATH, serializeVideos(videos));
  updateDataJsConfig(cfg);

  const untagged = videos.filter((v) => v.category === "uncategorized").length;

  console.log(`Wrote ${videos.length} video(s) to js/videos.generated.js.`);
  if (stillProcessing > 0) {
    console.log(`Skipped ${stillProcessing} video(s) still uploading/processing — re-run once they finish.`);
  }
  if (untagged > 0) {
    console.log(
      `${untagged} video(s) have no override yet and will show under "Uncategorized" — ` +
        `add entries for them in js/overrides.json (keyed by GUID) and re-run to tag them.`
    );
  }
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
